### ISSUE TITLE
Missing "Display Customers List with info" option

### ISSUE THREAD

**Issue by amardeeptoor13** [jorawarSinghNijjar/jaspreet-flour-mill#2]
There should be an option with which the information of previously registered customers can be shown. For example by clicking on "Display customers list", the table should be displayed which includes information about the customer's id, name, address, phone number, ration card no., date of birth, adhaar card no., Id proof.

The customer id is auto-generated. We don't know which id was assigned.

As a textbox in the "Add transaction" and "Wheat deposit" window asks for customer-id; in order to enter customer id there, there should be an option for "Display Customers List with info".

**Comment by jorawarSinghNijjar** [comment]
Resolved
