### ISSUE TITLE
Flour pickup quantity and Account wheat balance is not working correctly

### ISSUE THREAD

**Issue by msimranjit** [jorawarSinghNijjar/jaspreet-flour-mill#31]
These two values are showing 0 always.

**Comment by msimranjit** [comment]
![Capture2](https://user-images.githubusercontent.com/88874733/137418106-2b7dd229-47a9-4bf7-b128-a044bf10a985.PNG)

**Comment by jorawarSinghNijjar** [comment]
Which branch you are using currently for testing? Was it test branch?

**Comment by msimranjit** [comment]
I am testing on test
